# Generated by Django 3.1.2 on 2021-01-27 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Branch')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/pictures', verbose_name='Image')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
            ],
            options={
                'unique_together': {('city', 'street_address')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Name')),
                ('manager', models.BooleanField(default=False, verbose_name='Manager')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_wash_app.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_logo.jpg', upload_to='logo_pics', verbose_name='Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Company')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='car_wash_app.location', verbose_name='Location'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(manager=True), fields=('branch',), name='unique_together_manager_branch'),
        ),
    ]
