# Generated by Django 3.1.2 on 2021-01-30 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_wash_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='cartype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_wash_app.companyprofile', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='car_wash_app.cartype'),
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='car_wash_app.companyprofile', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='car_wash_app.location', verbose_name='Location'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('employee', 'start_date')},
        ),
        migrations.AddConstraint(
            model_name='employeeprofile',
            constraint=models.UniqueConstraint(condition=models.Q(manager=True), fields=('branch',), name='unique_together_manager_branch'),
        ),
    ]
