# Generated by Django 3.1.2 on 2021-01-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.SmallIntegerField(verbose_name='ID Number')),
                ('model_type', models.CharField(max_length=100, verbose_name='Car Model')),
                ('washing_cost', models.SmallIntegerField(verbose_name='Cost')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.AlterField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='car_wash_app.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, verbose_name='Customer')),
                ('order_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_wash_app.branch', verbose_name='Branch')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_wash_app.car', verbose_name='Car')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='car_wash_app.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'unique_together': {('employee', 'order_date')},
            },
        ),
    ]
