# Generated by Django 3.1.2 on 2021-01-31 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_wash_app', '0002_auto_20210130_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companyprofile', to=settings.AUTH_USER_MODEL, verbose_name='Company'),
        ),
    ]
