# Generated by Django 3.1.2 on 2021-01-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash_app', '0002_auto_20210128_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id_number',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='None', max_length=100, verbose_name='Brand'),
        ),
    ]
