# Generated by Django 3.1.2 on 2021-02-05 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_wash_app', '0004_auto_20210131_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='employee_order_percentage',
            field=models.IntegerField(default=10, verbose_name='Employee percetage from order price'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='car_wash_app.companyprofile', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeeprofile', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='washtype',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Wash Type'),
        ),
    ]
