# Generated by Django 3.1.2 on 2021-02-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash_app', '0005_auto_20210205_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End time'),
        ),
    ]
