# Generated by Django 3.1.2 on 2021-02-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash_app', '0006_auto_20210210_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='car_plate',
        ),
        migrations.AddField(
            model_name='coupon',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_coupon', to='car_wash_app.car', verbose_name='Car'),
        ),
    ]
