# Generated by Django 3.1.2 on 2021-02-14 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash_app', '0007_auto_20210213_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='cartype',
            name='washing_cost',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_coupon', to='car_wash_app.car', verbose_name='Car'),
        ),
        migrations.CreateModel(
            name='CompanyCarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washing_cost', models.SmallIntegerField(verbose_name='Cost')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_car_type', to='car_wash_app.cartype', verbose_name='Car Type')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_wash_app.companyprofile', verbose_name='Company')),
            ],
        ),
    ]
